# Generated by Django 3.2.5 on 2021-07-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('subcategory', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=6000)),
                ('images', models.CharField(max_length=6000)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
    ]
